# -*- coding: utf-8 -*-
"""airqualityproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pVQ2vBnSZx-iRBAdtYHsC_51PiHvn3n4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as pIt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import base
from sklearn.metrics import accuracy_score
#load Data set
df=pd.read_csv("air_quality_dataset.csv")
#display basic info
#df.info()
print('Basic information')
print(df.head(3))
print('\nSummary')
#df.describe()
#df.Location_Type.value_counts()
df.isnull().sum()
#df.Source_Label.value_counts()
#df.Location_Type.value_counts().plot(kind='bar')
df.hist()
df.Source_Label.value_counts().plot(kind='pie',autopct='%0.2f%%')
X=df.drop('Source_Label',axis=1)
X.head()
y=df.Source_Label
y.head()
#xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print(X_train.shape)
print(X_test.shape)
DT=DecisionTreeClassifier()
print(DT)
#DT.fit(X_train,y_train)
#prediction
#print("prediction")
#pred=DT.predict(X_test)
#print(pred)
#print(y_test.values)
#print("Accuracy")
#ac=accuracy_score(y_test,pred)
#print(ac)